<?php

return [
    'modules' => [
        'envios' => [
            'create' => 'envios.create',
            'read' => 'envios.view',
            'update' => 'envios.update',
            'delete' => 'envios.delete',
            'admin' => 'envios.admin.view',
        ],
        'vehiculos' => [
            'create' => 'vehiculos.create',
            'read' => 'vehiculos.view',
            'update' => 'vehiculos.update',
            'delete' => 'vehiculos.delete',
        ],
        'transportistas' => [
            'create' => 'transportistas.create',
            'read' => 'transportistas.view',
            'update' => 'transportistas.update',
            'delete' => 'transportistas.delete',
        ],
        'direcciones' => [
            'create' => 'direcciones.create',
            'read' => 'direcciones.view',
            'update' => 'direcciones.update',
            'delete' => 'direcciones.delete',
        ],
        'reportes' => [
            'read' => 'reportes.view',
            'export' => 'reportes.export',
        ],
        'lotes' => [
            'create' => 'lotes.create',
            'read' => 'lotes.view',
            'update' => 'lotes.update',
            'delete' => 'lotes.delete',
            'admin' => 'lotes.admin',
        ],
        'inventario' => [
            'create' => 'inventario.create',
            'read' => 'inventario.view',
            'update' => 'inventario.update',
            'delete' => 'inventario.delete',
            'admin' => 'inventario.admin',
        ],
        'usuarios' => [
            'create' => 'usuarios.create',
            'read' => 'usuarios.view',
            'update' => 'usuarios.update',
            'delete' => 'usuarios.delete',
            'admin' => 'usuarios.admin',
        ],
        'pedidos' => [
            'create' => 'pedidos.create',
            'read' => 'pedidos.view',
            'update' => 'pedidos.update',
            'delete' => 'pedidos.delete',
            'admin' => 'pedidos.admin',
        ],
        'ventas' => [
            'create' => 'ventas.create',
            'read' => 'ventas.view',
            'update' => 'ventas.update',
            'delete' => 'ventas.delete',
            'admin' => 'ventas.admin',
        ],
        'certificaciones' => [
            'create' => 'certificaciones.create',
            'read' => 'certificaciones.view',
            'update' => 'certificaciones.update',
            'delete' => 'certificaciones.delete',
            'admin' => 'certificaciones.admin',
        ],
        'catalogos' => [
            'create' => 'catalogos.create',
            'read' => 'catalogos.view',
            'update' => 'catalogos.update',
            'delete' => 'catalogos.delete',
            'admin' => 'catalogos.admin',
        ],
        'incidentes' => [
            'create' => 'incidentes.create',
            'read' => 'incidentes.view',
            'update' => 'incidentes.update',
            'delete' => 'incidentes.delete',
            'admin' => 'incidentes.admin',
            'resolve' => 'incidentes.resolve',
        ],
        'documentos' => [
            'create' => 'documentos.create',
            'read' => 'documentos.view',
            'update' => 'documentos.update',
            'delete' => 'documentos.delete',
            'admin' => 'documentos.admin',
        ],
        'rutas_multi' => [
            'create' => 'rutas_multi.create',
            'read' => 'rutas_multi.view',
            'update' => 'rutas_multi.update',
            'delete' => 'rutas_multi.delete',
            'admin' => 'rutas_multi.admin',
            'reorder' => 'rutas_multi.reorder',
        ],
        'asignaciones' => [
            'create' => 'asignaciones.create',
            'read' => 'asignaciones.view',
            'update' => 'asignaciones.update',
            'delete' => 'asignaciones.delete',
            'admin' => 'asignaciones.admin',
            'multiple' => 'asignaciones.multiple',
        ],
        'monitoreo' => [
            'read' => 'monitoreo.view',
            'simulate' => 'monitoreo.simulate',
            'admin' => 'monitoreo.admin',
        ],
        'panel_planta' => [
            'read' => 'panel_planta.view',
        ],
        'panel_transportista' => [
            'read' => 'panel_transportista.view',
        ],
        'panel_almacen' => [
            'read' => 'panel_almacen.view',
        ],
        'almacen_ingresos' => [
            'read' => 'almacen.ingresos.view',
            'create' => 'almacen.ingresos.create',
        ],
        'almacen_salidas' => [
            'read' => 'almacen.salidas.view',
            'create' => 'almacen.salidas.create',
        ],
        'almacen_movimientos' => [
            'read' => 'almacen.movimientos.view',
        ],
        'almacen_reportes' => [
            'read' => 'almacen.reportes.view',
        ],
    ],

    'role_permissions' => [
        'admin' => ['*'],
        'operador' => [
            'envios.create',
            'envios.view',
            'vehiculos.view',
            'vehiculos.create',
            'vehiculos.update',
            'vehiculos.delete',
            'transportistas.view',
            'transportistas.create',
            'transportistas.update',
            'transportistas.delete',
            'direcciones.view',
            'direcciones.create',
            'direcciones.update',
            'direcciones.delete',
            'reportes.view',
            'lotes.view',
            'lotes.update',
            'inventario.view',
            'inventario.update',
            'pedidos.view',
            'pedidos.update',
            'ventas.view',
            'ventas.update',
            'catalogos.view',
            'asignaciones.view',
            'asignaciones.create',
            'asignaciones.multiple',
            'rutas_multi.view',
            'rutas_multi.create',
            'rutas_multi.update',
            'documentos.view',
            'documentos.create',
            'incidentes.view',
            'incidentes.create',
            'incidentes.update',
            'incidentes.resolve',
            'monitoreo.view',
            'almacen.movimientos.view',
        ],
        'agricultor' => [
            'reportes.view',
            'inventario.view',
            'certificaciones.view',
            'certificaciones.create',
            'catalogos.view',
        ],
        'planta' => [
            'panel_planta.view',
            'lotes.view',
            'inventario.view',
            'envios.create',
            'envios.view',
            'envios.update',
            'asignaciones.view',
            'asignaciones.create',
            'asignaciones.multiple',
            'rutas_multi.view',
            'rutas_multi.create',
            'rutas_multi.update',
            'documentos.view',
            'documentos.create',
            'incidentes.view',
            'incidentes.create',
            'incidentes.resolve',
            'reportes.view',
            'ventas.view',
            'almacen.movimientos.view',
        ],
        'transportista' => [
            'panel_transportista.view',
            'envios.view',
            'envios.update',
            'asignaciones.view',
            'rutas_multi.view',
            'documentos.view',
            'documentos.create',
            'incidentes.view',
            'incidentes.create',
            'monitoreo.view',
            'reportes.view',
        ],
        'almacen' => [
            'panel_almacen.view',
            'inventario.view',
            'inventario.update',
            'envios.view',
            'documentos.view',
            'incidentes.view',
            'incidentes.create',
            'reportes.view',
            'monitoreo.view',
            'rutas_multi.view',
            'almacen.ingresos.view',
            'almacen.ingresos.create',
            'almacen.salidas.view',
            'almacen.salidas.create',
            'almacen.movimientos.view',
            'almacen.reportes.view',
        ],
    ],
];

